--commas inline                # Aligns with SwiftLint's no trailing comma rule
--insertlines preserve         # Keeps existing line breaks, avoids inserting unnecessary lines
--swiftversion 16.1            # Matches Swift version