# Excluded directories
excluded:
  - Pods
  - Carthage
  - Generated
  - ReaderIOSTests
  - ReaderIOSUITests

# Disabled rules
disabled_rules:
  - colon
  - comma
  - control_statement
  - todo
  - redundant_optional_binding
  - trailing_commas

trailing_comma: # Configures the trailing comma rule
  mandatory_comma: false

opening_brace: # Configures spacing for opening braces
  severity: warning
  ignore_multiline_function_signatures: true # Ignore multiline function signatures for brace placement

type_body_length:
  warning: 400 # Warning threshold
  error: 500 # Error threshold

file_length:
  warning: 600 # Warning threshold
  error: 1200 # Error threshold

type_name:
  min_length: 3 # Only warning for minimum length
  max_length:
    warning: 40 # Warning threshold
    error: 50 # Error threshold

identifier_name:
  min_length: # Only minimum length
    warning: 3 # Only error threshold
