//
//  .swiftformat.yml
//  ReaderIOS
//
//  Created by Jonas Schiessl on 12/3/24.
//

# Disable trailing commas
commas: inline

# Enforce no space before opening braces
brace-spacing: no-space

# Use Swift 16.1 version for compatibility
swiftversion: 16.1