# .swiftlint.yml
# ReaderIOS
# Created by Jonas Schiessl on 12/3/24.

disabled_rules: # Rule identifiers turned on by default to exclude from running
  - colon
  - comma
  - control_statement
  - todo

excluded:
  - ReaderIOSTests
  - ReaderIOSUITests

# If true, SwiftLint will check for updates after linting or analyzing.
check_for_updates: true

trailing_comma: # Configures the trailing comma rule
  required: false # Disable trailing commas in collection literals

opening_brace: # Configures spacing for opening braces
  severity: warning
  allow_multiline_func: false # Require braces to be on the same line as declarations
  space_before_brace: true # Require a single space before the opening brace

type_body_length:
  warning: 400 # Warning threshold
  error: 500 # Error threshold

file_length:
  warning: 600 # Warning threshold
  error: 1200 # Error threshold

# Naming rules can set warnings/errors for min_length and max_length
# Additionally, they can set excluded names
type_name:
  min_length: 3 # Only warning for minimum length
  max_length:
    warning: 40 # Warning threshold
    error: 50 # Error threshold
  excluded: # Names to exclude
    - iPad
  allowed_symbols: ["_"] # Allowed symbols in type names

identifier_name:
  min_length: # Only minimum length
    warning: 3 # Only error threshold
