--swiftversion 16.1

# Indentation
--indent 4
--tabwidth 4
--maxwidth 120

# Line breaks
--linebreaks lf

# Commas
--commas inline

# Braces
--wrapbraces inline

# Remove redundant self
--self remove

# Disable rules that conflict with SwiftLint
--disable redundantOptionalBinding
--disable trailingCommas

# Use SwiftLint's rules where possible
--swiftlint

# Other options ...
