# Generated by Django 5.1.5 on 2025-01-30 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("major_version", models.IntegerField()),
                ("minor_version", models.IntegerField()),
                ("localization", models.TextField(max_length=30)),
                ("is_released", models.BooleanField(default=False)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("major_version", "minor_version", "localization")},
            },
        ),
        migrations.CreateModel(
            name="Workbook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("chapters", models.JSONField()),
                ("pdf", models.FileField(upload_to="")),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.collection",
                    ),
                ),
            ],
            options={
                "unique_together": {("number", "collection")},
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.IntegerField()),
                (
                    "workbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.workbook"
                    ),
                ),
            ],
        ),
    ]
