# Generated by Django 5.1.5 on 2025-02-03 00:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='localization',
            field=models.TextField(max_length=5),
        ),
    ]
