# Generated by Django 5.1.5 on 2025-02-04 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_collection_localization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["id"]},
        ),
    ]
