# Generated by Django 5.1.5 on 2025-02-04 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_collection_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["-id"]},
        ),
    ]
