# Generated by Django 5.1.5 on 2025-02-04 17:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['major_version', 'minor_version', 'localization']},
        ),
    ]
