# Generated by Django 5.1.5 on 2025-02-04 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0005_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['-major_version', '-minor_version', 'localization']},
        ),
    ]
