# Generated by Django 5.1.5 on 2025-02-05 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0006_alter_collection_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workbook',
            options={'ordering': ['number', 'collection']},
        ),
        migrations.AlterField(
            model_name='workbook',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workbooks',
                                    to='core.collection'),
        ),
    ]
