# Generated by Django 5.1.6 on 2025-05-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_collection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='logs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
