name: Android Format

on:
  push:
    branches: [main]
    paths: ./ReaderAndroid
  pull_request:
    branches: [main]
    paths: ./ReaderAndroid

jobs:      
  format:
    name: Run Kotlin Formatting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v3

      #Step 2: Set up Java version
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x ./ReaderAndroid/gradlew

      - name: Run format checks
        working-directory: ./ReaderAndroid
        run: ./gradlew spotlessKotlinGradleCheck

      - name: Upload format reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: format-report
          path: |
            **/build/reports/spotless/
