name: Android Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    name: Run Kotlin Formatting
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Generate hash for the Android directory
      - name: Generate Android code hash
        id: android-hash
        run: |
          if [ -d "ReaderAndroid" ]; then
            find ReaderAndroid -type f | sort | xargs md5sum | md5sum | cut -d' ' -f1 > android_hash.txt
            echo "hash=$(cat android_hash.txt)" >> $GITHUB_OUTPUT
          else
            echo "hash=no-android-files" >> $GITHUB_OUTPUT
          fi

      # Step 3: Check cache based on the hash
      - name: Cache format check results
        id: cache-format
        uses: actions/cache@v3
        with:
          path: .cache/android-format
          key: android-format-${{ steps.android-hash.outputs.hash }}

      #Step 4: Set up Java version
      - name: Set up JDK
        if: steps.cache-format.outputs.cache-hit != 'true' && steps.android-hash.outputs.hash != 'no-android-files'
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      #Step 5: Grant permissions
      - name: Grant execute permission for gradlew
        if: steps.cache-format.outputs.cache-hit != 'true' && steps.android-hash.outputs.hash != 'no-android-files'
        run: chmod +x ./ReaderAndroid/gradlew

      #Step 6: Run formatting check
      - name: Run format checks
        if: steps.cache-format.outputs.cache-hit != 'true' && steps.android-hash.outputs.hash != 'no-android-files'
        working-directory: ./ReaderAndroid
        run: |
          ./gradlew spotlessKotlinGradleCheck
          mkdir -p ../.cache/android-format
          echo "Format check passed at $(date)" > ../.cache/android-format/result

      #Step 7: Report success
      - name: Report format status
        run: echo "Android formatting successful!"
