name: Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ktlint:
    name: Run Kotlin Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run ktlint checks
        run: ./gradlew spotlessKotlinCheck

      - name: Upload lint reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: |
            **/build/reports/spotless/
