name: iOS Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  swiftformat:
    name: Run iOS Formatting
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Generate hash for the iOS directory
      - name: Generate iOS code hash
        id: ios-hash
        run: |
          if [ -d "ReaderIOS" ]; then
            # Create a temporary file with all file paths
            find ReaderIOS -type f | sort > ios_files.txt
            # Calculate hash of all file contents concatenated
            cat ios_files.txt | while read file; do
              if [ -f "$file" ]; then
                cat "$file"
              fi
            done | md5 > ios_hash.txt
            echo "hash=$(cat ios_hash.txt)" >> $GITHUB_OUTPUT
          else
            echo "hash=no-ios-files" >> $GITHUB_OUTPUT
          fi

      # Step 3: Generate hash for the Android directory
      - name: Cache format check results
        id: cache-format
        uses: actions/cache@v3
        with:
          path: .cache/iOS-format
          key: iOS-format-${{ steps.iOS-hash.outputs.hash }}

      # Step 4: Install SwiftFormat or upgrade version
      - name: Install SwiftFormat
        if: steps.cache-format.outputs.cache-hit != 'true' && steps.iOS-hash.outputs.hash != 'no-iOS-files'
        run: |
          brew install swiftformat || brew upgrade swiftformat

      # Step 5: Run SwiftFormat
      - name: Check SwiftFormat
        if: steps.cache-format.outputs.cache-hit != 'true' && steps.iOS-hash.outputs.hash != 'no-iOS-files'
        working-directory: ./ReaderIOS
        run: |
          swiftformat . --lint --swiftversion 16.1 --config ../.swiftformat
          mkdir -p ../.cache/iOS-format
          echo "Format check passed at $(date)" > ../.cache/iOS-format/result

      #Step 6: Report success
      - name: Report format status
        run: echo "iOS format successful!"
