name: SwiftFormat

on:
  push:
    branches: [main]
    paths: ./ReaderIOS
  pull_request:
    branches: [main]
    paths: ./ReaderIOS

jobs:
  swiftformat:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

        # Step 2: Install SwiftFormat
      - name: Install SwiftFormat
        run: |
          brew install swiftformat || brew upgrade swiftformat

      # Step 3: Run SwiftFormat
      - name: Check SwiftFormat
        run: |
          swiftformat . --lint --swiftversion 16.1 --config ReaderIOS/.swiftformat
