name: SwiftFormat Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  swiftformat:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SwiftFormat
        run: |
          brew install swiftformat

      - name: Check SwiftFormat
        run: |
          swiftformat . --lint --swiftversion 16.1 --swiftlint
