name: SwiftLint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install SwiftLint
      - name: Install SwiftLint
        run: |
          brew install swiftlint brew upgrade swiftlint
      # Step 3: Run SwiftLint
      - name: Run SwiftLint
        run: |
          swiftlint --strict --config ./ReaderIOS/.swiftlint.yml
